// accessible by rootUrl/about
export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

const AboutPage = () => {
  return <div>About Page</div>;
};

export default AboutPage;
