export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

//  Difference b/w layout and template is -> layout preserve state
//  while template recreate dom while routing
