export const metadata = {
  title: 'Route Group Layout',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
      <b>Nested Route Group layout</b>
    </div>
  );
}
