// Accessible by rootUrl/profile
export const metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
};

const ProfilePage = () => {
  return (
    <div>Profile Page</div>
  )
}

export default ProfilePage